routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\diego1;
use App\Http\Controllers\citascont;
use App\Http\Controllers\horacontroller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("pacientereport" , diego1::class);

Route::resource("citasreport" , citascont::class);

Route::resource("horariocontroller" , horacontroller::class);  /* rurta que me transporta por todos las funciones de mi controller*/ 

resources/views/Paciente/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2> <strong>  CREAR NUEVO PACIENTE </strong>  </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('pacientereport.index') }}"> Regresar</a>
        </div>
        <br>
        <br>

        <form action="{{ route('pacientereport.store') }}" method="POST">
            @csrf

            <div class="row">
               
                <div>
                    <div class="form-group">
                        <strong>Nombres </strong>
                        <input type="varchar" name="nombres_paciente" class="form-control"
                            placeholder="Ingrese sus nombres">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong> Teléfono</strong>
                        <input type="varchar" name="telefono_paciente" class="form-control"
                            placeholder="Ingrese telefono">
                    </div>
                </div>
                
                <div>
                    <div class="form-group">
                        <strong>Email</strong>
                        <input type="varchar" name="email_paciente" class="form-control"
                            placeholder="Ingrese email">
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Ciudad:</strong>
                        <input type="varchar" name="ciudad_paciente" class="form-control"
                            placeholder="Ingrese ciudad">
                    </div>
                </div>
              
                <br>
                <br>
                <br>
                <br>


                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/Paciente/edit.blade.php
@extends('layouts.app')
@section('content')


   
    <div class="row">
    
        
        <div class="col-lg-12 margin-tb">
            

            
            <br />
            <div class="pull-left">
                <h2 align="center" > <strong>  EDITAR DATO CLIENTE  </strong>  </h2>
            </div>
            <br>

            <div class="container">

            <div class="pull-left">
                <a class="btn btn-primary" href="{{ route('pacientereport.index') }}"> Regresar</a>
            </div>
            <br>

        </div>
    </div>
    <form action="{{ route('pacientereport.update',$pacientereport->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="varchar" name="nombres_paciente" class="form-control" value="{{ $pacientereport->nombres_paciente }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Telefono :</strong>
                    <input type="varchar" name="telefono_paciente" class="form-control" value="{{ $pacientereport->telefono_paciente }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Email :</strong>
                    <input type="varchar" name="email_paciente" class="form-control" value="{{ $pacientereport->email_paciente }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Ciudad:</strong>
                    <input type="varchar" name="ciudad_paciente" class="form-control" value="{{ $pacientereport->ciudad_paciente }}">
                </div>
            </div>

            <br>
            <br>
            <br>
            <br>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/Paciente/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center"> <strong> DATOS DE PACIENTES</strong> </h1>
        <div>
            <a class="btn btn-success" href="{{ route('pacientereport.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th>Ciudad</th>
                <th>Acciones</th>
            </tr>
            @foreach ($pacientereport as $paciente)
                <tr>
                    <td>{{ $paciente->id}}</td>
                    <td>{{ $paciente->nombres_paciente }}</td>
                    <td>{{ $paciente->telefono_paciente }}</td>
                    <td>{{ $paciente->email_paciente }}</td>
                    <td>{{ $paciente->ciudad_paciente }}</td>
                   
                   
                    <td>
                        <!--  línea de codigo de iconos editar eliminar-->
                        
                     <div class="row">
                        <div class="col-sm-6"> 
                          
                        <a class="btn btn-primary" href="{{ route('pacientereport.edit',$paciente) }}">
                        <i class="fa-solid fa-pen-to-square"></i>  </a>

                    <form action="{{ route('pacientereport.destroy',$paciente->id) }}" method="POST">
                        @csrf
                    </div>
                   
                   <div class="col-sm-6">
                   

                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </div>
                    
                   
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection