routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\diego1;
use App\Http\Controllers\citascont;
use App\Http\Controllers\horacontroller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("pacientereport" , diego1::class);

Route::resource("citasreport" , citascont::class);

Route::resource("horariocontroller" , horacontroller::class);  /* rurta que me transporta por todos las funciones de mi controller*/ 

resources/views/Horarios/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br>
        <div align="center">
            <h2>CREAR HORARIO DE ATENCIÓN</h2>
        </div>
        <br>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('horariocontroller.index') }}"> Regresar</a>
        </div>
        <br>
        <br>

        <form action="{{ route('horariocontroller.store') }}" method="POST">          <!-- horario report _ dice _ lleveme al controlador-->  
            @csrf

            <div class="row">
               
                <div>
                    <div class="form-group">
                        <strong>Día Horario </strong>
                        <input type="date" name="dia_horario_atención" class="form-control"
                            placeholder="Ingrese el nombre">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong> Inicio Horario Atención</strong>
                        <input type="time" name="inicio_horario_atención" class="form-control"
                            placeholder="Ingrese fono">
                    </div>
                </div>
                
                <div>
                    <div class="form-group">
                        <strong>Fin Horario Atención</strong>
                        <input type="time" name="fin_horario_atención" class="form-control"
                            placeholder="Ingrese el color de la mesa deseada">
                    </div>
                </div>
                
                <br>
                <br>
                <br>
                <br>


                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>   <!-- submit  es un btn _ para enviar , crear, modificar -->
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/Horarios/edit.blade.php
@extends('layouts.app')
@section('content')


   
    <div class="row">
    
        
        <div class="col-lg-12 margin-tb">
            

            
            <br />
            <div class="pull-left">
                <h2 align="center" > <strong>  EDITAR HORARIO  </strong>  </h2>
            </div>
            <br>

            <div class="container">

            <div class="pull-left">
                <a  class="btn btn-primary" href="{{ route('horariocontroller.index') }}"> Regresar</a>


            </div>
            <br>

        </div>
    </div>
    <form action="{{ route('horariocontroller.update', $horarioo->id) }}" method="POST">

        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día:</strong>
                    <input type="varchar" name="dia_horario_atención" class="form-control" value="{{ $horarioo->dia_horario_atención }}">
                </div> 
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio :</strong>
                    <input type="time" name="inicio_horario_atención" class="form-control" value="{{ $horarioo->inicio_horario_atención }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora fin:</strong>
                    <input type="time" name="fin_horario_atención" class="form-control" value="{{ $horarioo->fin_horario_atención }}">
                </div>
            </div>

            <br>
            <br>
            <br>
            <br>


            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/Horarios/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center"> <strong> HORARIO DE ATENCIÓN </strong>   </h1>
        <div>
            <a class="btn btn-success" href="{{ route('horariocontroller.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th> Day </th>
                <th>Hora_Inicio</th>
                <th>Hora_Fin</th>
                
                <th>Acciones</th>
            </tr>
            @foreach ($horarios as $horarioo)
                <tr>
                    <td>{{ $horarioo->id}}</td>
                    <td>{{ $horarioo->dia_horario_atención}}</td>
                    <td>{{ $horarioo->inicio_horario_atención }}</td>
                    <td>{{ $horarioo->fin_horario_atención }}</td>
                    <td>
                    
                      <!--  línea de codigo de iconos editar eliminar-->
                        
                      <div class="row">
                        <div class="col-sm-6"> 
                          
                        <a class="btn btn-primary" href="{{ route('horariocontroller.edit',$horarioo) }}">
                        <i class="fa-solid fa-pen-to-square"></i>  </a>

                    <form action="{{ route('horariocontroller.destroy',$horarioo->id) }}" method="POST">
                        @csrf
                    </div>
                   
                   <div class="col-sm-6">
                   

                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </div>
                    </form> 

                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection