routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\diego1;
use App\Http\Controllers\citascont;
use App\Http\Controllers\horacontroller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("pacientereport" , diego1::class);

Route::resource("citasreport" , citascont::class);

Route::resource("horariocontroller" , horacontroller::class);  /* rurta que me transporta por todos las funciones de mi controller*/ 

resources/views/citas/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br>
        <div align="center">
            <h2>CREAR NUEVA CITA</h2>
            <BR>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('citasreport.index') }}"> Regresar</a>
        </div>
        <br>
       

        <form action="{{ route('citasreport.store') }}" method="POST">
            @csrf

            <div class="row">
               
                <div>
                    <div class="form-group">
                        <strong>Fecha_Cita </strong>
                        <input type="Date" name="fecha_cita" class="form-control"
                            placeholder="Ingrese el nombre">
                    </div>
                </div>

                <br>
                <br>

                <div>
                    <div class="form-group">
                        <strong> Hora_Cita </strong>
                        <input type="Time" name="hora_cita" class="form-control"
                            placeholder="Ingrese fono">
                    </div>
                </div>

             

                <div>
             
                
                <br>
                <br>


                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/citas/edit.blade.php
@extends('layouts.app')
@section('content')


   
    <div class="row">
    
        
        <div class="col-lg-12 margin-tb">
            
            <br />
            <div class="pull-left">
                <h2 align="center" > <strong>  EDITAR CITA  </strong>  </h2>
            </div>
            <br>

            <div class="container">

            <div class="pull-left">
                <a class="btn btn-primary" href="{{ route('citasreport.index') }}"> Regresar</a>
            </div>
            <br>

        </div>
    </div>
    <form action="{{ route('citasreport.update',$citasreport->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Fecha_Cita:</strong>
                    <input type="varchar" name="fecha_cita" class="form-control" value="{{ $citasreport->fecha_cita }}">
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora_Cita :</strong>
                    <input type="varchar" name="hora_cita" class="form-control" value="{{ $citasreport->hora_cita }}">
                </div>
            </div>

            <br>
            <br>
            <br>
            <br>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/citas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">CITAS </h1>
        <div>
            <a class="btn btn-success" href="{{ route('citasreport.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Fecha_Cita</th>
                <th>Hora_Cita</th>
                <th>Acciones</th>
            </tr>
            @foreach ($citasreport as $citass)
                <tr>
                    <td>{{ $citass->id}}</td>
                    <td>{{ $citass->fecha_cita }}</td>
                    <td>{{ $citass->hora_cita }}</td>

                    <td>
                        <!--  línea de codigo de iconos editar eliminar-->
                        
                     <div class="row">
                        <div class="col-sm-6"> 
                          
                        <a class="btn btn-primary" href="{{ route('citasreport.edit',$citass) }}">
                        <i class="fa-solid fa-pen-to-square"></i>  </a>

                    <form action="{{ route('citasreport.destroy',$citass->id) }}" method="POST">
                        @csrf
                    </div>
                   
                   <div class="col-sm-6">
                   

                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button> 
                    </div>
                    
                   
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection
                   
                  